server:
  port: 8081


spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices2
    username: root
    password: Mysqsk45@123
    driver-class-name: com.mysql.cj.jdbc.Driver		
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    import: optional:configserver:http://localhost:8084
#eureka:
#  client:
#   service-url:
#    defaultZone: http://localhost:8585/eureka/   # URL of Eureka server
#   fetch-registry: true
#   register-with-eureka: true
#  instance:
#     prefer-ip-address: true